# Generated by Django 4.2.7 on 2025-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique notification identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_confirmation", "Order Confirmation"),
                            ("order_shipped", "Order Shipped"),
                            ("order_delivered", "Order Delivered"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("payment_failed", "Payment Failed"),
                            ("welcome", "Welcome"),
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                            ("low_stock", "Low Stock Alert"),
                            ("vendor_approval", "Vendor Approval"),
                            ("vendor_rejection", "Vendor Rejection"),
                            ("product_review", "Product Review"),
                            ("refund_processed", "Refund Processed"),
                            ("newsletter", "Newsletter"),
                            ("promotion", "Promotion"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "message",
                    models.TextField(help_text="Notification message content"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Message ID from external provider",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Response from notification provider",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data used for template rendering",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for notification failure",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_payment_updates", models.BooleanField(default=True)),
                ("email_promotions", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("email_product_reviews", models.BooleanField(default=True)),
                ("sms_order_updates", models.BooleanField(default=False)),
                ("sms_payment_updates", models.BooleanField(default=False)),
                ("sms_promotions", models.BooleanField(default=False)),
                ("push_order_updates", models.BooleanField(default=True)),
                ("push_payment_updates", models.BooleanField(default=True)),
                ("push_promotions", models.BooleanField(default=True)),
                ("in_app_order_updates", models.BooleanField(default=True)),
                ("in_app_payment_updates", models.BooleanField(default=True)),
                ("in_app_promotions", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject or notification title",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Template body with placeholders"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available template variables",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["template_type"],
                        name="notificatio_templat_b63ef6_idx",
                    ),
                    models.Index(
                        fields=["is_active"],
                        name="notificatio_is_acti_f33840_idx",
                    ),
                ],
            },
        ),
    ]
