# Generated by Django 4.2.7 on 2025-09-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="products.productattribute",
            ),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(fields=["slug"], name="product_att_slug_ade8f1_idx"),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["is_variant"], name="product_att_is_vari_a34182_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["is_filterable"], name="product_att_is_filt_1ec862_idx"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.tag"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                limit_choices_to={"role": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["slug"], name="brands_slug_6a4b1c_idx"),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["is_active"], name="brands_is_acti_101dba_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariantattribute",
            index=models.Index(
                fields=["variant", "attribute"],
                name="product_var_variant_8c1f69_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariantattribute",
            unique_together={("variant", "attribute")},
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="product_var_sku_3a95f0_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["price"], name="product_var_price_75df2c_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["stock_quantity"],
                name="product_var_stock_q_ecefab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_active"], name="product_var_is_acti_c7d489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"],
                name="product_var_product_b96575_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "is_approved"],
                name="product_rev_product_eb9ba2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["rating"], name="product_rev_rating_fb8943_idx"),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["is_verified_purchase"],
                name="product_rev_is_veri_09399c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["created_at"], name="product_rev_created_1dfa58_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "user")},
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"],
                name="product_ima_product_c8c86a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["variant"], name="product_ima_variant_3b8a6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(
                fields=["attribute", "value"],
                name="product_att_attribu_d01970_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together={("attribute", "value")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_slug_5e91f2_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_sku_fe2039_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="products_status_a30e64_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured"], name="products_is_feat_19b203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["vendor"], name="products_vendor__a6b4c0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_4083ff_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_brand_i_0d1950_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="products_created_e1ba5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="categories_is_acti_aae090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent"], name="categories_parent__7983b2_idx"),
        ),
    ]
